### PR TITLE
Fix 8.13 warnings

### PR DESCRIPTION
**Pull request by Casteran**
-  Replaced unused match variables with underscores
-  Add locality attribute to Hint commands (export or local)
-  Removed the Admitted

### CODE REVIEW

**Comment by Casteran** [comment]
Do we need to maintain compatibility with 8.10 and  8.11 ? Is it a good practice to tag master as 8.11 before merging ?
I presume there are more elegant/standard solutions ...

**Comment by palmskog** [comment]
It's generally fine to drop compatibility with earlier versions of Coq, since we have releases we can refer to. Following the conventions used for this repository so far, the tag/release for Coq 8.13 would be called `v8.13.0`.

**Comment by Casteran** [comment]
So, what I could do  is to change  references to Coq versions in coq-coq-art.opam, meta.yml and .github/workflows/coq-ci.yml ?
Then tag v8.13.0 once merged ?

**Comment by palmskog** [comment]
@Casteran the boilerplate is supposed to be generated from meta.yml via our [templates](https://github.com/coq-community/templates). In the interest of time, I did this in a commit to this branch.

**Comment by palmskog** [comment]
For the record, if the code is all ready for release (looks like it to me), indeed all that is remaining is to merge the PR and tag `v8.13.0`.

**Pull request merged**
